# Generated by Django 3.1.6 on 2021-02-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
