# Generated by Django 3.1.6 on 2021-02-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('FullName', models.CharField(max_length=10)),
                ('Id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=10)),
            ],
        ),
    ]
